# Generated by Django 4.0.1 on 2022-01-31 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareas',
            name='comentarios',
            field=models.CharField(max_length=200, verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='date_expiration',
            field=models.DateTimeField(null=True, verbose_name='EXPIRA'),
        ),
    ]
