# Generated by Django 4.0.1 on 2022-02-01 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_tareas_comentarios_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='tareas',
        ),
        migrations.AddField(
            model_name='tareas',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.usuarios'),
        ),
    ]
